[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    max-age=600,
    must-revalidate'''
