name: Scheduled build
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        env:
          TOKEN: ${{ secrets.NETLIFY_DAILY_BUILD }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${TOKEN}
